# Stage 1: Build the application
FROM alpine:latest AS builder

WORKDIR /usr/src/app

COPY donetick .
COPY config/selfhosted.yaml config/local.yaml ./config/

# Stage 2: Create a smaller runtime image
FROM alpine:latest

# Install timezone package and su-exec for stepping down from root
RUN apk --no-cache add tzdata su-exec

# Install necessary CA certificates
RUN apk --no-cache add ca-certificates libc6-compat

# Copy the binary and config folder from the builder stage
COPY --from=builder /usr/src/app/donetick /donetick
COPY --from=builder /usr/src/app/config /config
COPY entrypoint.sh /entrypoint.sh

# Set environment variables
ENV DT_ENV="selfhosted"

# Default PUID and PGID values (can be overridden at runtime). Use these to
# ensure the files on the volumes have the permissions you need.
ENV PUID=1000
ENV PGID=1000

# Expose the application port
EXPOSE 2021

ENTRYPOINT ["/entrypoint.sh"]
CMD ["/donetick"]
